### ISSUE TITLE
Copy-pasting in the editor

### ISSUE THREAD

**Issue by grahampugh** [mikaellofgren/RecipeBuilder#1]
Nice work on this app! 

I just downloaded it and attempted to create a `.jss` recipe. First thing I noticed is that the parent recipe is always `com.github.dataJAR-recipes.pkg.Coot`.

Secondly, if I want to add extra keys to the `JSSImporter` processor, the text is white-on-white. For example, I tried to copy-paste the `groups` key so that I could create an `exclusion_groups` key, but it comes out white-on-white.

I don't know if you intended to allow editing in the app, or the idea is more to export it to a different editor, but this is my experience so far anyway.

Keep up the good work, this could be a useful addition to the AutoPkg toolset.

**Comment by mikaellofgren** [comment]
Thanks for that. 1. I guess that I need a placeholder text for the ParentRecipe. 2. I guess you are using Dark Mode, try to switch to see if its works better.

**Comment by mikaellofgren** [comment]
I also notice that if I run Finalize the text goes black...

**Comment by grahampugh** [comment]
Yes, it's better in Light Mode.

**Comment by mikaellofgren** [comment]
Fixed, parent recipe, added Placeholder text instead.
