### ISSUE TITLE
Open does not function

### ISSUE THREAD

**Issue by jazzace** [mikaellofgren/RecipeBuilder#3]
Thanks for your efforts on this.

I tried to open a recipe I had built and saved in RecipeBuilder. Opening the recipe using File > Open resulted in no recipe being opened (and no feedback).

**Comment by mikaellofgren** [comment]
Thanks. Whats the location of the recipe, and what OS? I thinking maybe some sandboxing problem...

**Comment by jazzace** [comment]
macOS Catalina 10.15.5, the RecipeBuilder Output directory (or the default AutoPkg/Recipes directory). Intriguing. On further testing, I can open one recipe with the Open command, but all subsequent requests in a session are non-functional. It does not seem to be tied to which recipe I am opening (i.e. probably not a permissions issue).

**Comment by mikaellofgren** [comment]
Been trying to replicate the issue on a Mojave and then upgraded to Catalina. Seems to work here, but I did notice if I close the main window, there is no way of getting it back even from open command. Thats something that I have to look into to...

**Comment by jazzace** [comment]
Yes, I did have the "main window" closed. I did further testing and that is actually the failure condition: Open does not work if the main window is closed. (In my previous testing, I opened the first file with the main window present but closed it prior to the second attempt to open a file.

**Comment by mikaellofgren** [comment]
Just released 1.02 thats brings back the main window by creating new file or open a file.
